### ISSUE TITLE
汇总信息只能在body写完以后再tail写入么，哪怕是writeHead也只是读取head模板写入文件尾么

### ISSUE THREAD

**Issue by qsdavid** [alipay/rdf-file#21]

**Comment by quhongwei** [comment]
1. 汇总信息字段是在body数据读写过程中，将body指定字段累加， 汇总信息字段可以放在头部也可以放在尾部
2. 在读文件时，readHead 或者readtTail 获取汇总字段，可以跟body读取时累加的汇总值进行比较
3. 在写文件时，由于文件时顺序写入， 如果汇总字段放在尾部，没有问题，写完body后获取汇总值写入尾部，如果汇总值放在头部，我们做法是body单独写入body文件，获取汇总值在写入头文件，最后将头和body和成一个完整文件
4. 哪怕是writeHead也只是读取head模板写入文件尾么？对于这句话我没有理解是啥意思？

**Comment by qsdavid** [comment]
感谢答复，提供的思路已经能解决问题了
