### ISSUE TITLE
自定义定长模板问题

### ISSUE THREAD

**Issue by qsdavid** [alipay/rdf-file#28]
您好，有个问题想问下，我现在按照国标fund模板，自己定义了一个新的不需要头部垂直数据的定长文件模板json，但是导出的时候定长解析不生效，都是一行所有数据写入，如果换成fund模板倒是可以，但是fund被其他文件已经使用了，不能修改，想问下如果要自定义一个定长模板，除了protocol文件还有哪些需要添加注意的地方呢，谢谢~

**Comment by quhongwei** [comment]
1.protocol文件存在地址正确
2. 数据定义模板正确定义协议类型
参考：https://github.com/alipay/rdf-file/wiki/%E5%8D%8F%E8%AE%AE%E5%B8%83%E5%B1%80%E6%89%A9%E5%B1%95%E6%9C%BA%E5%88%B6%E4%B9%8Bxml%E5%AE%9A%E4%B9%89
有问题随时联系我们， 你也可以把你自定义的协议模板发给我们看看

**Comment by qsdavid** [comment]
协议模板就是fund 头部只留totalcount那行，其他不变，地址是对的，已经跟过源码

**Comment by qsdavid** [comment]
问题已经解决，需要添加对应模板的properties format文件，对定长文件来说好像是必要的

**Comment by quhongwei** [comment]
是的，对字段做特殊处理，都可以扩展format

**Comment by qsdavid** [comment]
好的，谢谢答复了~
