### ISSUE TITLE
rdf是否支持同一个文件中有多种规则的解析

### ISSUE THREAD

**Issue by lwjaiyjk** [alipay/rdf-file#3]
就是一个文件中有多行，可能有3中规则类型，根据每一行第一个字段的值来判断其属于哪一个规则，然后再进行解析？？

**Comment by quhongwei** [comment]
目前不支持， 目前rdf-file类似关系数据库的二维表， 行中每个字段含义是已经定义好了

**Comment by quhongwei** [comment]
> 就是一个文件中有多行，可能有3中规则类型，根据每一行第一个字段的值来判断其属于哪一个规则，然后再进行解析？？

目前不支持， 目前rdf-file类似关系数据库的二维表， 行中每个字段含义是已经定义好了

**Comment by lwjaiyjk** [comment]
我在你们的基础上增加了这个功能（单文件多模板），改动也不是很大，仅仅是模板配置改一下，其他和你们现在一样，你们可以看一下https://github.com/lwjaiyjk/rdf-file

**Comment by quhongwei** [comment]
> 我在你们的基础上增加了这个功能（单文件多模板），改动也不是很大，仅仅是模板配置改一下，其他和你们现在一样，你们可以看一下https://github.com/lwjaiyjk/rdf-file

非常👍，根据用户反馈我们后续考虑下是否加入这个功能 !

**Comment by quhongwei** [comment]
基于外部反馈及内部评估，将支持单文件多模板功能

**Comment by quhongwei** [comment]
release by https://github.com/alipay/rdf-file/releases/tag/v2.2.0
