### ISSUE TITLE
支持创建本地临时文件加上threadId防止并发

### ISSUE THREAD

**Issue by iminright** [alipay/rdf-file#32]
支持创建本地临时文件加上threadId防止并发

**Comment by quhongwei** [comment]
1.oss写通过不同线程号，可以防止本地并发冲突，最终保证上传到oss文件完整，但是最后一个上传为有效文件
2. nas/本地并发组件无法控制，可以通过先写到带线程好的临时目录，最后rename到目标目录

**Comment by quhongwei** [comment]
release by 2.2.1
