### ISSUE TITLE
导出文件时如果需要自定义分隔符为unicode字符如何处理

### ISSUE THREAD

**Issue by qsdavid** [alipay/rdf-file#33]
RT，最近碰到一种文件，分隔符是用unicode字符\u0001来分隔的，导入的时候可以自定义分隔处理器，但是导出的时候好像没有相关的处理器能够自定义处理，经过blank判断后，trim过后的unicode字符就变为空串了，怎么解决呢，请教下，谢谢~

**Comment by quhongwei** [comment]
这个分隔符比较特殊，我们得研究下是否可以支持

**Comment by qsdavid** [comment]
好的，目前看来就是判空分隔符的时候进行了trim所以导致不支持unicode字符了

**Comment by quhongwei** [comment]
https://github.com/alipay/rdf-file/tree/20190320-ColumnSplit   在这个分支对unicode的空格字符\u0001进行了支持，是否可以拉下这个分支，用你们文件进行下测试

**Comment by quhongwei** [comment]
release by 2.2.1
