### ISSUE TITLE
发现一个导致会打开过太多文件的问题

### ISSUE THREAD

**Issue by qsdavid** [alipay/rdf-file#34]
RT，FileValidator 的validate方法实现中，貌似打开的reader没有关闭，在处理大批量文件的时候，会导致文件句柄打开过多导致系统异常 ProtocolFileValidator类中的方法，可以看下是不是有相关的问题

**Comment by quhongwei** [comment]
确实是， 修复代码已提交master， 非常感谢！！！

**Comment by qsdavid** [comment]
多谢修复了，您看什么时候发布一个新的版本，我们好进行同步更新一下

**Comment by quhongwei** [comment]
估计周五

**Comment by quhongwei** [comment]
release by 2.2.1
