### ISSUE TITLE
2.2.0版本后ProtocolFileValidator逻辑问题

### ISSUE THREAD

**Issue by qsdavid** [alipay/rdf-file#37]
RT，发现一个问题，比较源码后，发现2.1.3版本和之后版本的ProtocolFileValidator类验证的逻辑不太一样，会导致带有头部配置的xml模板实际json不配置头部信息时，仍然会进行行数和头部行数的校验导致报错，2.1.3版本头部为空时会有boolean值进行校验拦截，之后的版本去除了这部分的逻辑

**Comment by quhongwei** [comment]
感谢反馈， 修复代码已提交master，并补充这个场景测试用例ProtocolFileValidatorTest4， 后续会发布一个修正版本

**Comment by qsdavid** [comment]
好的
