### ISSUE TITLE
`开放式基金业务数据交换协议`的链接失效

### ISSUE THREAD

**Issue by xingguang2013** [alipay/rdf-file#44]
文档中，`https://github.com/alipay/rdf-file/wiki` 关于`开放式基金业务数据交换协议`的链接已失效。

**Comment by quhongwei** [comment]
已更新

**Comment by xingguang2013** [comment]
`https://github.com/alipay/rdf-file/wiki/协议布局扩展机制` , `https://github.com/alipay/rdf-file/wiki/组件内置协议之fund` , `https://github.com/alipay/rdf-file/wiki/组件内置协议之fund` 中还有关于`开放式基金业务数据交换协议`的失效链接

**Comment by quhongwei** [comment]
多谢，已更新
