### ISSUE TITLE
某些类在 toString 方法中使用 StringBuffer

### ISSUE THREAD

**Issue by xingguang2013** [alipay/rdf-file#46]
在以下类中的方法中使用 java.lang.StringBuffer ：
* `com/alipay/rdf/file/meta/FileColumnTypeMeta.java:65` 
* `com/alipay/rdf/file/model/FileConfig.java:361`
* `com/alipay/rdf/file/protocol/RowDefinition.java:120`
* `com/alipay/rdf/file/function/ColumnFunctionWrapper.java:135`
* `com/alipay/rdf/file/function/ColumnFunctionWrapper.java:114`
* `com/alipay/rdf/file/meta/FileColumnMeta.java:125`
* `com/alipay/rdf/file/meta/FileMeta.java:391`

是否可以改成 StringBuilder ?

**Comment by quhongwei** [comment]
我觉得都可以

**Comment by xingguang2013** [comment]
线程非安全情况下 StringBuilder 不是更好的选择么？还是有别的考虑？

**Comment by quhongwei** [comment]
除了FileConfig其他类都线性安全，FileConfig作为参数对象不能多线程共享

**Comment by xingguang2013** [comment]
好的 谢谢
