### ISSUE TITLE
使用 ScheduledExecutorService 来替代 Timer

### ISSUE THREAD

**Issue by xingguang2013** [alipay/rdf-file#47]
多线程并行处理定时任务时， `Timer` 运行多个 `TimeTask` 时，只要其中之一没有捕获抛出的异常，其它任务便会自动终止运行，使用 `ScheduledExecutorService` 则没有这个问题。 是否可以使用 `ScheduledExecutorService` 来替代？

`com.alipay.rdf.file.preheat.OssPreheatProtocolReaderWrapper` 类的 `Timer` 属性

**Comment by quhongwei** [comment]
1.  理论上Timer是OssPreheatProtocolReaderWrapper成员变量，每个Timer只会添加一个TimeTask， close后会销毁，不应该影响其他读任务， 
2.  能把报错堆栈贴出来吗？是什么原因导致 TimeTask执行报错

**Comment by xingguang2013** [comment]
没有发生报错异常，只是在看源码时发现的，而且根据阿里巴巴编程规约也不建议用 Timer ，所以就提了个 issus问问

**Comment by quhongwei** [comment]
恩恩 ， 阿里巴巴编程规约只是指出Timer使用不当容易出错，正确使用不会有问题
