### ISSUE TITLE
如下的文件格式协议能不能支持

### ISSUE THREAD

**Issue by javachuxiao** [alipay/rdf-file#49]
id,eventId,taskId,totalAmount,status
1,Ea123,Ts123,5,A
id,eventId,taskId,amount
2,aa123,as123,5,D
......
第一行为文件头的描述，第二行为文件头的属性值，第三行为文件体的字段描述，第四行及后面都是文件体的内容，要解析的是文件头的内容（即第二行值）和文件体的内容，即第4行及后面的所有文件行。

**Comment by quhongwei** [comment]
1. 目前组件内置协议不满足，需要自定义协议  https://github.com/alipay/rdf-file/wiki/%E5%8D%8F%E8%AE%AE%E5%B8%83%E5%B1%80%E6%89%A9%E5%B1%95%E6%9C%BA%E5%88%B6%E4%B9%8Bxml%E5%AE%9A%E4%B9%89
2. 对于头描述输出之前没有遇到这种场景，组件内置没有实现，但是可以扩展组件内置函数参考对body描述输出BodyColumnFunction即可， 函数扩展 https://github.com/alipay/rdf-file/wiki/%E5%8D%8F%E8%AE%AE%E5%B8%83%E5%B1%80%E6%89%A9%E5%B1%95%E6%9C%BA%E5%88%B6%E4%B9%8BFunction%E5%87%BD%E6%95%B0
3. 对于头尾描述数据输出，后续组件考虑纳为内置功能

**Comment by quhongwei** [comment]
在 https://github.com/alipay/rdf-file/tree/20191129-functionext 分支实现扩展
1.  新增内置协议cm
2. 实现更通用的字段信息扩展函数columnInfo（用于替换bodycolumn）
3. 需要一段时间完善场景测试和测试用例，后发布新的版本
4. 如等不及或者不想升级版本可以参考分支代码自行扩展

**Comment by quhongwei** [comment]
release by 2.2.6
