### ISSUE TITLE
文件出现负数金额，无法序列化

### ISSUE THREAD

**Issue by Grt1228** [alipay/rdf-file#52]
出现负数金额，NumberFormatException

**Comment by quhongwei** [comment]
请提供下数据定义模板和出错字段

**Comment by quhongwei** [comment]
fund协议中不支持负数，是因为基金标准定义时负数有专门的标志位去标记， 但是从功能上是可以只支持的

**Comment by quhongwei** [comment]
参考测试用例：com.alipay.rdf.file.writer.FundFileWriterTest#testWriterNegative 
release by 2.2.7
