### ISSUE TITLE
OssPreheatProtocolFileMerger merge无head文件头文件writer null空指针问题

### ISSUE THREAD

**Issue by karott** [alipay/rdf-file#53]
![image](https://user-images.githubusercontent.com/3212080/87126523-e6cd2400-c2be-11ea-992b-a57543e45fa7.png)
执行路径：merge时会直接进入mergeBodyStream，不会调用ensureOpen 创建writer，导致没有写入器

**Comment by quhongwei** [comment]
多谢反馈

**Comment by quhongwei** [comment]
release by 2.2.7
