### ISSUE TITLE
DE模板指定是GBK，但是如果文件内容是全英文的话，生成文件还是UTF-8

### ISSUE THREAD

**Issue by Bigming1007** [alipay/rdf-file#59]

**Comment by iminright** [comment]
单元测试显示确实有问题
```
@Test
public void testWriter_test() throws Exception {
      String filePath = tf.getRoot().getAbsolutePath();
      System.out.println(filePath);

      FileConfig config = new FileConfig(new File(filePath, "test.txt").getAbsolutePath(),
              "/writer/template/template5.json", new StorageConfig("nas"));
      FileWriter fileWriter = FileFactory.createWriter(config);

      Map<String, Object> body = new HashMap<String, Object>();
      body.put("OriginalAppSheetSerialNo", "abc");
      fileWriter.writeRow(body);
      fileWriter.close();
  }
```
模版：
`{
  "head": [
    "version|version|default:1.0",
    "totalCount|rows|Integer"
  ],
  "body": [
    "OriginalAppSheetSerialNo|OriginalAppSheetSerialNo"
  ],
  "lineBreak": "\r\n",
  "tail": [
    "fileEnd|数据文件尾部字符|default:END"
  ],
  "fileEncoding":"GBK",
  "protocol": "DE"
}`
秋秋看下呢

**Comment by quhongwei** [comment]
比较好奇如何确定生成的文件编码还是uft-8的。
文件内容本身没有标记是哪种编码类型， 当然有些开源组件可以根据文件内容尝试推断编码类型，但是不是百分百准确。
对英文来讲一个字母占用一个字节在所有编码下都一样， 但对同一个中文文字在不同的编码下会可能占用不通的字节。 所以对中文写的编码和读编码一致才不会导致乱码。对全英文写我理解用一种编码写入，用另一种编码打开应该都没有问题，因为每个字符都占用一个字节，都能正常解析。

**Comment by quhongwei** [comment]
比较好奇如何确定生成的文件编码还是uft-8的。
文件内容本身没有标记是哪种编码类型， 当然有些开源组件可以根据文件内容尝试推断编码类型，但是不是百分百准确。
对英文来讲一个字母占用一个字节在所有编码下都一样， 但对同一个中文文字在不同的编码下会可能占用不通的字节。 所以对中文写的编码和读编码一致才不会导致乱码。对全英文写我理解用一种编码写入，用另一种编码打开应该都没有问题，因为每个字符都占用一个字节，都能正常解析。

**Comment by iminright** [comment]
结论：文件格式基于推测并不准确，全英文文件utf-8或者gbk都不影响代码使用和人工阅读
