### ISSUE TITLE
期望兼容数据文件动态增加字段的场景

### ISSUE THREAD

**Issue by karott** [alipay/rdf-file#67]
场景1：实际模板定义字段后，如果数据文件在最后增加了新的字段，但暂时不需要消费该字段，希望能够兼容，不要报模板定义列数与实际字段列数不一致的错

场景2：目前好像模板定义字段顺序必须与文件字段顺序一致，希望能够可以顺序不一致，字段名相同就行

**Comment by quhongwei** [comment]
收到
场景1，简单想了下应该问题不大
场景2，模板定义字段顺序必须与文件字段顺序一致， 文件行中只存储文件内容不保存字段信息，文件序列化与反序列化都按模板定义字段顺序处理， 所以看来不能做到顺序不一致字段名相同， 还请列举下具体使用场景来看看是否有普遍性？

**Comment by quhongwei** [comment]
release by 2.2.9
