### ISSUE TITLE
oss存储中，filestorage使用download下载时，如果key为文件夹，返回对象不存在

### ISSUE THREAD

**Issue by luannanxian** [alipay/rdf-file#70]
`        srcOSSPath = toOSSPath(srcOSSPath);
        List<String> fileNames = listAllFiles(srcOSSPath);
        if (isExist(srcOSSPath)) {
            fileNames.add(srcOSSPath);
        } else {
            throw new RdfFileException("rdf-file:FileOssStorage.download# oss donwLoad srcOSSPath=" + srcOSSPath + " 不存在",
                RdfErrorEnum.NOT_EXSIT);
        }`

key实际存在，isExist(srcOSSPath)返回不存在

**Comment by quhongwei** [comment]
release by 2.29
