### ISSUE TITLE
提示错误: 执行xxx方法是出错

### ISSUE THREAD

**Issue by aa987746356** [alipay/rdf-file#79]
版本 2.2.10
RdfFunction类, execute方法, 55行
![image](https://user-images.githubusercontent.com/45580742/202632680-5b79fa0b-d8e0-44e8-97d1-1621ea7e0eee.png)

**Comment by quhongwei** [comment]
堆栈发下，是自定义了函数吗？

**Comment by aa987746356** [comment]
我的意思是 这个提示语错了. 执行xxx[方法是]出错, ->方法时 .

**Comment by quhongwei** [comment]
是的， 收到， 3ks
