### ISSUE TITLE
读取文件时，如何指定不可见字符做为分割符

### ISSUE THREAD

**Issue by yuelin-peng** [alipay/rdf-file#80]
读取文件时，有一个文件的分割符是\033，我在配置文件中，protocol=SP，指定了columnSplit=\033，但是解析时，分隔符没有起效果，得到的只有一列，请问需要制定不可见字符作为分割符需要怎么处理呢？非常感谢各位解答

{
    "body":[
        "account|账号",
        "currtype|币种",
...
    ],
    "protocol":"SP",
    "columnSplit":"\033"
}

**Comment by quhongwei** [comment]
理论上是可以， 可以先用这个模板写个文件， 在读取看看，是不是可以， 写的文件是不是你们要的

**Comment by yuelin-peng** [comment]
> 理论上是可以， 可以先用这个模板写个文件， 在读取看看，是不是可以， 写的文件是不是你们要的

从测试结果上看不行，但是我去额外设置配置中的分割符也不行，看备注是要raw模式设置才能生效

**Comment by quhongwei** [comment]
DeSeperatorFileWriterTest 看看这个测试用例

**Comment by quhongwei** [comment]
抽空写个了个单测，写读都正常的
https://github.com/alipay/rdf-file/blob/master/rdf-file-core/src/test/java/com/alipay/rdf/file/writer/SpSeperatorFileWriterTest.java

**Comment by yuelin-peng** [comment]
> 抽空写个了个单测，写读都正常的 https://github.com/alipay/rdf-file/blob/master/rdf-file-core/src/test/java/com/alipay/rdf/file/writer/SpSeperatorFileWriterTest.java

非常感谢详细的回答，我跑下单测
