### ISSUE TITLE
function机制怎么用在写文件中

### ISSUE THREAD

**Issue by SCUT-FMS** [alipay/rdf-file#81]
能否给出几个function机制运用在写文件时的test，仓库中的例子有点少 不是很能理解用法

**Comment by quhongwei** [comment]
![image](https://user-images.githubusercontent.com/3232378/218651899-81ee08da-6de0-4274-8fe0-46c5eff43af0.png)

协议文件中 ${} 定义的就是函数计算输出定义

**Comment by quhongwei** [comment]
![image](https://user-images.githubusercontent.com/3232378/218652431-b017d8c9-f7f1-4169-af8d-6c217e708db8.png)

内置实现这几个函数
