### ISSUE TITLE
新增processor怎么使用

### ISSUE THREAD

**Issue by SCUT-FMS** [alipay/rdf-file#82]
我想自己实现一个processor,在写文件前对数据进行处理，请问一下要怎么才能使用到自己的processor,我看代码里好像是只能从配置文件里获取默认processor，但我是第三方引用依赖，没办法修改配置文件，请问要怎么做

**Comment by quhongwei** [comment]
第一种方式
![image](https://user-images.githubusercontent.com/3232378/218660075-bbea8b27-2450-40dc-a4f6-f94a46fbdf46.png)
配置在同等目录下， 会自动合并

第二种：com.alipay.rdf.file.model.FileConfig#processorKeys  手动指定

**Comment by SCUT-FMS** [comment]
第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定
这种方法我添加了一个key值，那怎么跟我的processor绑定呢

举个例子 我的processor为myprocessor， key值为"myprocessor"
FileConfig.addProcessorKey(“myprocessor”)

**Comment by SCUT-FMS** [comment]
> 第一种方式 ![image](https://user-images.githubusercontent.com/3232378/218660075-bbea8b27-2450-40dc-a4f6-f94a46fbdf46.png) 配置在同等目录下， 会自动合并
> 
> 第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定

第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定

**Comment by SCUT-FMS** [comment]
> 第一种方式 ![image](https://user-images.githubusercontent.com/3232378/218660075-bbea8b27-2450-40dc-a4f6-f94a46fbdf46.png) 配置在同等目录下， 会自动合并
> 
> 第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定
第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定
这种方法我添加了一个key值，那怎么跟我的processor绑定呢
举个例子 我的processor为myprocessor， key值为"myprocessor"
FileConfig.addProcessorKey(“myprocessor”)

**Comment by SCUT-FMS** [comment]
> 第一种方式 ![image](https://user-images.githubusercontent.com/3232378/218660075-bbea8b27-2450-40dc-a4f6-f94a46fbdf46.png) 配置在同等目录下， 会自动合并
> 
> 第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定




按照第二种：com.alipay.rdf.file.model.FileConfig#processorKeys 手动指定
这种方法我添加了一个key值，那怎么跟我的processor绑定呢
举个例子 我的processor为myprocessor， key值为"myprocessor"
FileConfig.addProcessorKey(“myprocessor”)

**Comment by quhongwei** [comment]
![image](https://user-images.githubusercontent.com/3232378/218684614-5b7c722d-a025-4a07-be88-654653179bec.png)
如上spi扩展配置下

**Comment by SCUT-FMS** [comment]
> ![image](https://user-images.githubusercontent.com/3232378/218684614-5b7c722d-a025-4a07-be88-654653179bec.png) 如上spi扩展配置下

请教一下 作为第三方依赖的时候 这个配置文件不是只读的吗 我怎么才能改的了

**Comment by quhongwei** [comment]
自己系统中，classloader下，建相同文件目录和文件即可
