### ISSUE TITLE
请问原生的writer支持按json格式输出吗？

### ISSUE THREAD

**Issue by yuelin-peng** [alipay/rdf-file#83]
非常感谢回答

**Comment by quhongwei** [comment]
原生的可以， writeLine是啥就是啥， 是json就是json
有兴趣也可以扩展协议，把writeRow(Map), map序列化成json

**Comment by yuelin-peng** [comment]
> 原生的可以， writeLine是啥就是啥， 是json就是json 有兴趣也可以扩展协议，把writeRow(Map), map序列化成json

好的
