### ISSUE TITLE
异常解决

### ISSUE THREAD

**Issue by SCUT-FMS** [alipay/rdf-file#84]
rdf-file#模板不存在 templatePath=classpath:/Users/cgb-parse.json 请问这是什么原因

**Comment by quhongwei** [comment]
classpath协议加载， 项目类路径下文件，你这个文件放在磁盘的绝对路径下

**Comment by SCUT-FMS** [comment]
> classpath协议加载， 项目类路径下文件，你这个文件放在磁盘的绝对路径下

我修改了路径后不会报这个错了 但好像filereader没有生效，配置里没有分隔符，导致我读取一行数据的时候读不了
![Uploading 截屏2023-02-17 10.14.51.png…]()

**Comment by SCUT-FMS** [comment]
> classpath协议加载， 项目类路径下文件，你这个文件放在磁盘的绝对路径下

我修改了路径后不会报这个错了 但好像filereader没有生效，配置里没有分隔符，导致我读取一行数据的时候读不了
<img width="1588" alt="截屏2023-02-17 10 14 51" src="https://user-images.githubusercontent.com/49604423/219534580-46489875-edb9-474c-88b5-910242f42514.png">

**Comment by quhongwei** [comment]
cgb-parse.json内容发出来看下, 默认com.alipay.rdf.file.meta.TemplateConfig#columnSplit=”|“

**Comment by SCUT-FMS** [comment]
> 

{
  "body": [
    "tradeNO|交易流水号|Required",
    "account|监管户银行帐号|Required",
    "tradeDate|交易日期|Required|Date:yyyy-MM-dd HH:mm:ss",
    "drcrf|借贷标记",
    "summaryCode|摘要码",
    "currtype|币种",
    "amount|交易金额|Required|BigDecimal",
    "balance|账户余额",
    "recipaccount|对方帐号",
    "recipname|对方户名",
    "message|附言",
    "status|状态|Required"
  ],
  "protocol": "SP",
  "columnSplit":"\\|"
}

**Comment by quhongwei** [comment]
fileconfig没有分隔符正常， fileconfig设置了分隔符优先级最高，   com.alipay.rdf.file.util.RdfFileUtil#getColumnSplit决策了使用哪个分隔符

**Comment by SCUT-FMS** [comment]
> fileconfig没有分隔符正常， fileconfig设置了分隔符优先级最高， com.alipay.rdf.file.util.RdfFileUtil#getColumnSplit决策了使用哪个分隔符

com.alipay.rdf.file.exception.RdfFileException: rdf-file#RowColumnHorizontalCodec.deserialize fileConfig=FileConfig[type=protocol,filepath=/tmp/cgb/trade/20221024/ea/03065811_08_20221024_01_001.csv,fileDataType=BODY,fileEncoding=gbk,templatePath=data_template/cgb-parse.json,templateEncoding=utf-8,lineBreak=null,storageType=nas,summaryEnable=true,createEmptyFile=false, offset=0,length=1014,isAppend=false, is=null], line=20221024000000085928|9550880483314400128|2022-10-22 13:58:14|02|杞处瀛樺叆|CNY|323|323|6214620421000536176|閫犳暟鎬″瘨棣檤娴嬭瘯杞处|0模板定义列数=1, 实际列数=12
这是错误信息 还是分割不了 请问可能是什么原因

**Comment by quhongwei** [comment]
文件内容发出来看下

**Comment by SCUT-FMS** [comment]
> 文件内容发出来看下

交易流水号|监管户银行账号|交易日期|借贷标记|摘要码|币种|交易金额|账户余额|对方账号|对方户名|附言|状态
20221024000000085928|9550880483314400128|2022-10-22 13:58:14|02|转账存入|CNY|323|323|6214620421000536176|造数怡寒香|测试转账|0
20221024000000085970|9550880483314400128|2022-10-22 13:59:29|02|转账存入|CNY|11329|11652|6214620421000536176|造数怡寒香|测试转账|0
20221024000000086270|9550880483314400128|2022-10-22 14:07:10|02|转账存入|CNY|11330|21980|6214620421000536176|造数怡寒香|测试转账|0
20221024000000086272|9550880483314400128|2022-10-22 14:07:14|02|转账存入|CNY|11331|33311|6214620421000536176|造数怡寒香|测试转账|0
20221024000000086284|9550880483314400128|2022-10-22 14:10:27|02|转账存入|CNY|11332|43640|6214620421000536176|造数怡寒香|测试转账|0
20221024000000086287|9550880483314400128|2022-10-22 14:11:51|02|转账存入|CNY|11333|54973|6214620421000536176|造数怡寒香|测试转账|0
~

**Comment by SCUT-FMS** [comment]
> 文件内容发出来看下

<img width="1121" alt="截屏2023-02-17 15 35 27" src="https://user-images.githubusercontent.com/49604423/219580127-c16fd714-dc71-45a2-9c20-062e5dd0b98d.png">

**Comment by quhongwei** [comment]
大概率是乱码导致， 确认下写入文件的编码， 默认组件是按com.alipay.rdf.file.util.RdfFileUtil#getFileEncoding=utf-8读取

**Comment by SCUT-FMS** [comment]
> 大概率是乱码导致， 确认下写入文件的编码， 默认组件是按com.alipay.rdf.file.util.RdfFileUtil#getFileEncoding=utf-8读取

是utf-8的 还是会出异常

**Comment by quhongwei** [comment]
第一行中文文件头去掉， sp协议不能解析这个
