### ISSUE TITLE
配置文件添加字段的自定义生成能力

### ISSUE THREAD

**Issue by Eriri** [alipay/rdf-file#86]
- 目前痛点：解析账单后进行清洗需要写业务代码，每次接入新类型账单都需要进行代码适配，改动量大
- 期望功能：希望可以在配置文件中添加generate属性，通过配置generate支持一定的dsl语言能力，在配置文件中通过描述dsl语句即可做到字段清洗与生成，无需代码改动
- 魔改实践：我最近尝试在代码中接入antlr组件进行dsl能力适配，测试了通过配置文件的generate属性几个字段进行处理生成新字段，在列元信息解析时引入对应生成规则语法树，但是发现wrtie进行serialize时仅会传field字段不会传rowBean，无法通过某一行几个字段进行生成，所以修改了serialize的输入传入了rowBean，同时修改了ColumnFunction在输出value时判断生成规则是否存在并进行输出，改动diff在https://github.com/Eriri/rdf-file/pull/1/commits/a14ba474d89bed0be9531d385f2e76ae075f7dff  ，辛苦帮忙看下这种改动方法（传入rowBean）是否正确呢

**Comment by quhongwei** [comment]
所有字段写一行的会传rowBean， 你看的是一个字段写一行的时没有传

**Comment by Eriri** [comment]
这种想要根据输入一整行的数据做类似mysql类操作生成新的输出字段的能力，现在有办法通过自定义function的方式实现吗；或者这个逻辑是否能放在getProperty取得field值时进行操作呢， 希望可以提供一些思路

**Comment by quhongwei** [comment]
新的输出字段的能力是在字段的类型转换或者格式化，还是说输入a,b,c字段输出e,f字段。
转换或者格式化组件设计是支持的，可以通过RdfFileColumnTypeSpi和RdfFileFormatSpi做处理。
输入a,b,c字段输出e,f字段， 理论也可以可以参考com.alipay.rdf.file.function.ColumnInfoFunction，在de和fund协议定义中有对这个扩展的使用例子，
