### ISSUE TITLE
特殊分割字符无法分割

### ISSUE THREAD

**Issue by SCUT-FMS** [alipay/rdf-file#89]
我的分割符是 |@| 没办法正常分割 想问一下对于这个字符是要做什么处理才能正常分割

**Comment by quhongwei** [comment]
![image](https://user-images.githubusercontent.com/3232378/228401089-6c106e13-5133-463a-b8c3-8fcc66cff35a.png)
数据定义模板中配置分隔符

**Comment by SCUT-FMS** [comment]
> ![image](https://user-images.githubusercontent.com/3232378/228401089-6c106e13-5133-463a-b8c3-8fcc66cff35a.png) 数据定义模板中配置分隔符

我配置了这样的内容 但分割符似乎没有起效
{
  "body": [
    "id|序号",
    "account|监管户银行帐号|Required",
    "billDate|账务日期|Date:yyyyMMdd",
    "tradeTime|交易发生的系统时间｜Date:yyyyMMddHHmmss",
    "flowID|交易CCBS流水号｜Required",
    "creditAmount|借方金额|BigDecimal",
    "debitAmount|贷方金额｜BigDecimal",
    "balance|交易后账户余额|BigDecimal",
    "oppositeBankNo|对方交易行号",
    "oppositeBankName|对方交易行名",
    "recipeAccount|对方帐号",
    "recipeName|对方户名",
    "remark|备注"
  ],
  "protocol": "SP",
  "columnSplit":"|@|"
}

**Comment by SCUT-FMS** [comment]
我的待分割文本文件是gbk编码 这个会有影响吗
<img width="1212" alt="截屏2023-03-29 10 09 51" src="https://user-images.githubusercontent.com/49604423/228408300-f39b74b3-21fb-4ede-bad0-40998c78fd7b.png">

**Comment by quhongwei** [comment]
读取文件的编码，跟写入文件本身编码要一致， 不然可能会有问题

**Comment by SCUT-FMS** [comment]
我debug了一下 内容如下 读取数据的时候还是没办法成功 读到的row是null
<img width="1387" alt="截屏2023-03-29 11 41 35" src="https://user-images.githubusercontent.com/49604423/228421283-809657bd-f276-4f20-b41b-26e442d28f66.png">
<img width="1553" alt="截屏2023-03-29 11 41 49" src="https://user-images.githubusercontent.com/49604423/228421337-1825a162-01ad-4fd2-95ef-3aa76ab66f2c.png">
<img width="1553" alt="截屏2023-03-29 11 42 01" src="https://user-images.githubusercontent.com/49604423/228421444-cb351586-2896-4f60-a301-52278becc3b7.png">
<img width="1616" alt="截屏2023-03-29 11 42 24" src="https://user-images.githubusercontent.com/49604423/228421470-de9c6d01-e47e-4fb2-9f14-beef151d24f3.png">

**Comment by quhongwei** [comment]
不太能够确定问题所在， 你可以先写一个文件比较比较， 在读取那个文件
